// Icons the server may name (constants.py) plus the ones the shell uses. Listing them keeps the
// bundle small: importing the whole icon set would add hundreds of KB.
import {
  AlertTriangle, Archive, BookA, BookOpenText, Building2, Check, ChevronDown, ChevronLeft, ChevronRight,
  CircleCheck, ClipboardList, Database, ExternalLink, Eye, FileText, FileType, Folder, FolderOpen, FolderTree,
  Gauge, HardDrive, Inbox, Info, KeyRound, Layers, LayoutDashboard, Library, Loader2, LogOut, Menu, Moon,
  Network, Pencil, Plus, RefreshCw, Save, ScrollText, Search, Settings, ShieldCheck, Sun, Trash2, Users,
  Warehouse, X, Upload, UserPlus, Copy, Link2, MessageSquare, Undo2, CalendarPlus, PackageCheck, Send, Clock, Printer, Download, SlidersHorizontal, Bookmark, Command, FileImage, FileSpreadsheet, File, CornerDownLeft,
} from "lucide-vue-next";

export const icons = {
  "alert-triangle": AlertTriangle,
  archive: Archive,
  "book-a": BookA,
  "book-open-text": BookOpenText,
  "building-2": Building2,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-check": CircleCheck,
  "clipboard-list": ClipboardList,
  database: Database,
  "external-link": ExternalLink,
  eye: Eye,
  "file-text": FileText,
  "file-type": FileType,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-tree": FolderTree,
  gauge: Gauge,
  "hard-drive": HardDrive,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  library: Library,
  loader: Loader2,
  "log-out": LogOut,
  menu: Menu,
  moon: Moon,
  network: Network,
  pencil: Pencil,
  plus: Plus,
  "refresh-cw": RefreshCw,
  save: Save,
  "scroll-text": ScrollText,
  search: Search,
  settings: Settings,
  "shield-check": ShieldCheck,
  sun: Sun,
  "trash-2": Trash2,
  users: Users,
  warehouse: Warehouse,
  x: X,
  upload: Upload,
  printer: Printer,
  download: Download,
  sliders: SlidersHorizontal,
  bookmark: Bookmark,
  command: Command,
  "file-image": FileImage,
  "file-spreadsheet": FileSpreadsheet,
  file: File,
  "corner-down-left": CornerDownLeft,
  "user-plus": UserPlus,
  copy: Copy,
  link: Link2,
  "message-square": MessageSquare,
  undo: Undo2,
  "calendar-plus": CalendarPlus,
  "package-check": PackageCheck,
  send: Send,
  clock: Clock,
};

export const iconFor = (name) => icons[name] || FileText;
